[package]
name = "dbl-venus-visualization"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.7"
color-eyre = "0.6.1"
eframe = { version = "0.18.0", features = ["dark-light"] }
egui_extras = "0.18.0"
postcard-cobs = "0.2.0"
time = "0.3.9"
tokio = { version = "1.18.2", features = ["rt", "parking_lot", "io-util", "time"] }
tokio-serial = "5.4.3"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
