[package]
name = "dbl-venus-visualization"
version = "0.1.0"
edition = "2021"

[dependencies]
postcard-cobs = "0.2.0"
color-eyre = "0.6.1"
eframe = { version = "0.18.0", features = ["dark-light"] }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
argh = "0.1.7"
tokio = { version = "1.18.2", features = ["full"] }
tokio-serial = "5.4.3"
